### ISSUE TITLE
Headers in html_block Tokens aren't given slugs

### ISSUE THREAD

**Issue by shellscape** [valeriangalliat/markdown-it-anchor#105]
When headers (`<h2 .../>` etc) are within tokens with `.type === 'html_block'` the plugin doesn't assign IDs nor create slugs. I've been using Vue's README.md as a baseline for that https://github.com/vuejs/vue/blob/dev/README.md

**Comment by valeriangalliat** [comment]
Wow that's pretty cool! I just found out on your other issue that npm was using markdown-it and a similar approach to parse HTML headers, I had no idea.

At that point I would just reuse npm's implementation, e.g. `md.use(require('@npmcorp/marky-markdown/lib/plugin/html-heading'))`, even though the implementation is likely to give unexpected results on edge cases, if it works good enough for npm it's probably going to be ok in most cases.

I'll add a line to document that in the readme because it's good to know, but I wouldn't add that code to markdown-it-anchor unless it actually works with edge cases too.

But at that point I think it would be easier to add the anchors on the HTML rather than during the Markdown parsing phase, e.g.:

```js
const { parse } = require('node-html-parser')
const root = parse(html)

for (const h of root.querySelectorAll('h1,h2,h3,h4,h5,h6')) {
  const slug = h.getAttribute('id') || slugify(h.textContent)
  h.setAttribute('id', slug)
  h.insertAdjacentHTML('afterbegin', `<a class="header-anchor" href="#${slug}">#</a> `)
}

console.log(root.toString())
```

**Comment by shellscape** [comment]
Yeah I think we can close this one. I do want to note that NPM's code doesn't pick up headers with attributes, as their regex is pretty constrained. I'm left wondering if they use this code at all anymore. See the Vue rendered readme here: https://www.npmjs.com/package/vue. I ran that readme through marky-markdown and that `Supporting Vue.js` header wasn't assigned an anchor, yet on npmjs.com it is. I ended up sticking with an implementation that uses cheerio to catch that during markdown parsing - the number one reason was `markdown-it-toc-done-right` compatibility - if the headers are added after the fact, they don't make it into the toc.

**Comment by valeriangalliat** [comment]
Oh wow, right. The more I think about it, the more I feel like all of this (anchors, TOC) should be done at the HTML level instead of Markdown, which is likely how GitHub not only has anchors and TOC on Markdown files, but also RST, and Org mode

**Comment by shellscape** [comment]
That's a valid point.
