### ISSUE TITLE
`id`'s for Paragraphs Too?

### ISSUE THREAD

**Issue by ToniWonKanobi** [valeriangalliat/markdown-it-anchor#14]
### Question

Have you considered allowing `id`'s to be applied to paragraphs---not just headings?
### Problem
- For a lot of my blog posts/writing (especially short passages of text), I don't use headings.
- In those situations, it would be nice to permalink to a specific area of my post/writing, rather than _just_ link to the entire post itself.
### Suggestions

You could implement it in a similar way as you do for headings.
- You could leverage `slugify` in the same way
- Have it take up to the first five words and create a string from that
  - If the paragraph has less than five words, just create an `id` with as many words as the paragraph has
    - If the paragraph has only four words, make the `id` with those four words
  - If a paragraph has more than five words, take the first five words and create a `id` from that
  - If two paragraphs have the same first five words, add a sixth word, and so on
#### Example

Consider the following Markdown source:

``` md
# Heading <!-- What `markdown-it-anchor` does already -->

This is a paragraph. <!-- Four words only -->

This is yet another paragraph. <!-- Five words -->

This is yet another paragraph that has more than five words. <!-- More than five words, and the first five are the same as the above example paragraph -->
```

This could be parsed to the following:

``` html
<h1 id="heading">Heading</h1> <!-- Expected default/current behavior -->

<p id="this-is-a-paragraph">This is a paragraph.</p> <!-- Since the Markdown source is a paragraph with only four words, those four words are incorporated into the `id` -->

<p id="this-is-yet-another-paragraph">This is yet another paragraph.</p> <!-- Five words, so the `id` gets those exact five words -->

<p id="this-is-yet-another-paragraph-that">This is yet another paragraph that has more than five words.</p> <!-- The Markdown source has more than five words, so the first five would be incorporated into the `id`. But since the previous paragraph would have that same `id`, `markdown-it-anchor` should add a sixth word. If another `id` with that string exists already, add another word (so the `id` would have seven words), etc. -->
```

---

Dave Winer made this concept famous: [WinerLinks](https://www.drupal.org/project/winerlinks) (there's even a WordPress plugin)!

But I know `markdown-it-anchor` could have a more intelligent approach than the WordPress plugin.

I'd like to know your thoughts :)

**Comment by valeriangalliat** [comment]
I never thought of this before but I like the idea. Though I'm really not sure how to implement this.

Slugifying is nice for headings because they're usually fairly short; it allows a deterministic way to predict the ID, allowing to reference a heading from a link in the Markdown file itself and being confident it will not change unless you update your title (which can happen but not as often as a paragraph). For paragraphs, it would be too long, so as you said we can strip them, but then add more words if the beginning is the same... it feels less predictable/solid than for titles. I see other implementations generate an ID from a hash of the content itself and paragraph position, so using the 5 first words or more would still be a more robust solution!

Also we don't expect the same anchor style for a heading than for a paragraph at all, so we would need two render functions.

And just to keep track, you mention paragraphs only here, but you also said "all block level elements" [on Twitter](https://twitter.com/ToniWonKanobi/status/687657501769113600); I cannot think of a way to make this work as blocks can be contained in blocks... this would result in a lot of duplicate IDs and be a mess with "adding the next word" in case of a duplicate. Plus I don't think anyone wants to display an anchor at the end of every single block element. :smile:

In summary, this would require having a different ID generation function for paragraphs, and a different rendering function for paragraphs. This could pretty much live in a separate plugin `markdown-it-winerlinks`. Though significant parts of the logic of `markdown-it-anchor` could be reused, so I'm not sure about this.

I'll keep thinking of this idea, and how to refactor the code to support both cases, without adding too much bloat. Maybe something like `markdown-it-anchor/title` and `markdown-it-anchor/paragraph`, both using a top-level function with the common logic, just configuring a token filtering function (headings, header level, paragraphs), rules to hook into, and different options for the slugification function, `uniqueSlug` that is not yet configurable, rendering function and options.

There's really something interesting to do here, I'm excited by this refactoring!

**Comment by ToniWonKanobi** [comment]
1. Block-level elements:

    Yeah, I realized while creating the Issue here that implementing this for block-level elements would be rather wonky, and largely unnecessary.

2.  I was thinking specifically for images (`<img>` or `<figure>`-wrapped).

    For instance, if I wanted to `id` and `img`, however you implemented my suggestion (`markdown-it-paragraph` or whatever you call it) would already take care of images, since pure Markdown already places images on a line by themselves:

 ```md
![](image.png)
```

    parse:

 ```html
<p><img src="image.png" alt="" title="" /></p>
```

    (Pure [Markdown](http://daringfireball.net/projects/markdown/syntax#img))

3. For the life of me, I couldn't think of any other block-level elements that have a Markdown shorthand. In other words, since most every other block-level element would have to use actual HTML markup, it doesn't make sense to do the auto `id`'s, since we could place that in the raw HTML anyways:

 ```md
This is a paragraph written in Markdown.

<div id="important-paragraph"> <!-- Might as well just put the `id` here by hand, since we're having to write HTML anyways -->

This is a paragraph written in Markdown, but with special styling based on its parent `<div>`

</div>
```

**Comment by nagaozen** [comment]
Hi @ToniWonKanobi, have you tried `markdown-it-attrs`? For me, it looks more adequate.

**Comment by ToniWonKanobi** [comment]
@nagaozen I just got a notification for this Issue, and it's crazy because I don't even remember even writing all this 😆

Your suggestion is a nice one, but kind of more work than what I was suggesting. (The whole point of what I was original suggesting was to have a `markdown-it` plugin that *auto*-generated `id`'s for paragraphs and/or images/figures ;)
