### ISSUE TITLE
Add anchor after heading text

### ISSUE THREAD

**Issue by danielgtaylor** [valeriangalliat/markdown-it-anchor#3]
Right now, the anchor is always added **before** the heading text:

```html
<!-- Currently -->
<h1><a href="...">P</a>I am a header</h1>

<!-- What I would like to see -->
<h1>I am a header<a href="...">P</a></h1>
```

This makes is easy to hide the anchor until mouse over and doesn't require shifting headings outside of their container to keep alignment on the left side (for LTR text). Ultimately it should probably just be an option.

Is this something you'd be willing to add? Otherwise I think this plugin is great!

**Comment by valeriangalliat** [comment]
Agreed.

Initially, I put it before the heading because I wanted to mimic how GitHub renders anchors in Markdown files, but it indeed requires some styling to look decent.

I think putting the anchor after the header would be a more sensible default (and it would be consistent with how [Python Markdown is doing with the `permalink` option](http://pythonhosted.org/Markdown/extensions/toc.html)). Having the anchor before the header should still be possible with an option.

Since this is a breaking change I'm releasing 2.0.0 with this feature.

**Comment by danielgtaylor** [comment]
@valeriangalliat thanks!
