### ISSUE TITLE
Nested anchor slugs

### ISSUE THREAD

**Issue by LeviRosol** [valeriangalliat/markdown-it-anchor#30]
Is there an option to use nesting when generating slugs? ie:

```
# Tacos

## Beef

# Burritos

## Beef
```

resulting in:

```
<h1 id="tacos">Tacos</h1>
<h2 id="taco-beef"Beef</h2>
<h1 id="burritos">Burritos</h1>
<h2 id="burritos-beef"Beef</h2>
```

**Comment by valeriangalliat** [comment]
There is none, but I believe you could hack one together using the `callback`, a custom `slugify` function, and some shared state between them. I don't have the time to do a PoC right now though

**Comment by LeviRosol** [comment]
I worked on this a bit last night in a branch of your app, and then refactored it this morning and I'm pretty pleased with the results. I did add it as a configurable option, added a bunch of tests due to all of the parent / child / sibling / grandparent type scenarios, and updated the readme. IMO, it's feature complete.

That said, the code looks like ass. There's just no great way to keep logic like this looking good, but a fresh set of eyes may be ideal for a refactor.

I'll be pushing a PR shortly

**Comment by valeriangalliat** [comment]
Thanks for making a PR!

I'm not sure I want to keep that logic inside the core code though, I'd rather keep it as simple as possible.

I tried my idea of using the `callback` and `slugify` but since `callback` is called after `slugify` it doesn't work... however just by adding something like `preCallback` before the `slugify` call, we could be able to implement that externally.

Here's the patch to markdown-it-anchor:

```diff
diff --git a/index.js b/index.js
index d3d295e..2bf6f55 100644
--- a/index.js
+++ b/index.js
@@ -72,11 +72,16 @@ const anchor = (md, opts) => {
 
         let slug = token.attrGet('id')
 
+        if (opts.preCallback) {
+          slug = opts.preCallback(token, { slug, title }) || slug
+        }
+
         if (slug == null) {
           slug = uniqueSlug(opts.slugify(title), slugs)
-          token.attrPush(['id', slug])
         }
 
+        token.attrPush(['id', slug])
+
         if (opts.permalink) {
           opts.renderPermalink(slug, opts, state, tokens.indexOf(token))
         }
```

And an example test file adding that functionally just through `preCallback`:

```js
const md = require('markdown-it')()
const anchor = require('markdown-it-anchor')

const titles = []

function getCurrentTitles () {
  const currentTitles = [titles[0]]

  for (let i = 1; i < titles.length; i++) {
    if (titles[i].level > titles[i - 1].level) break
    currentTitles.unshift(titles[i])
  }

  return currentTitles
}

function preCallback (token, { slug, title }) {
  const level = Number(token.tag.substr(1))
  titles.unshift({ token, level, slug, title })
  const currentTitles = getCurrentTitles()
  return currentTitles.map(t => t.title).map(anchor.defaults.slugify).join('-')
}

md.use(anchor, { preCallback })

const input = `
# Tacos

## Beef

# Burritos

## Beef
`

const output = md.render(input)

console.log(output)
```

It outputs the following:

```html
<h1 id="tacos">Tacos</h1>
<h2 id="tacos-beef">Beef</h2>
<h1 id="burritos">Burritos</h1>
<h2 id="burritos-beef">Beef</h2>
```

The code is not perfect, it does not pass your (very exhaustive) test suite, because I hacked that quickly instead of porting your code there, but you get the main idea. :)

I have to think about adding that `preCallback` option, and how to name it, or maybe using events or something? But that's more the path I would take for that kind of feature.

**Comment by LeviRosol** [comment]
Understandable. fwiw, i've seen a number of other anchor plugins where this topic has been discussed, but no viable answer was found / created. I totally understand your thinking in keeping the plugin simple, however, if you're putting the effort into making a solution that uses outside code, why not incorporate it so others don't screw it up?

I did just update my PR with additional logic / tests for a scenario I hadn't tested for. It certainly didn't help with the complexity, but it appears to work.
