### ISSUE TITLE
Doesn't work with markdown-it-toc

### ISSUE THREAD

**Issue by MoOx** [valeriangalliat/markdown-it-anchor#4]
If I use [markdown-it-toc](https://github.com/samchrisinger/markdown-it-toc) after, your plugin just do nothing.
And if I use it before, your plugin add anchor, but something seems broken

```html
<h2>
  <a id="Installation_3"></a>
  <a class="markdownIt-Header-anchor" href="#installation">#</a>
  Installation
</h2>
```

Any idea how to get anchor links + toc ?

My options

```js
markdownIt({
html: true,
  linkify: true,
  typographer: true,
  highlight: (code, lang) => {
    code = code.trim()
    // language is recognized by highlight.js
    if (lang && hljs.getLanguage(lang)) {
      return hljs.highlight(lang, code).value
    }
    // fallback to auto
    return hljs.highlightAuto(code).value
  })
        .use(markdownItToc)
        .use(markdownItAnchor, {
          permalink: true,
          permalinkClass: "markdownIt-Header-anchor",
          permalinkSymbol: "#",
          permalinkBefore: true,
        })
```

**Comment by valeriangalliat** [comment]
markdown-it-anchor and markdown-it-toc were not developed to be compatible, so I'm not surprised they don't play well together by default.

* markdown-it-toc *overrides* the heading renderer, so if you use it after markdown-it-anchor, it will effectively do nothing (markdown-it-anchor renderer never called).
* markdown-it-anchor *extends* the heading renderer, calling the previous one after modifying the token chain. This is why, when called after, the second anchor is added. However markdown-it-toc ignores the attributes from the heading token when rendering, that's why markdown-it-anchor heading  ID is never added.
* Both plugins have a different way to manage IDs. markdown-it-anchor adds an ID on the heading, while markdown-it-toc adds an empty anchor with an ID.
* Both plugins have a different way to slugify the title to generate an ID. markdown-it-anchor allow to customize this function with the `slugify` option.

According to this, you *can* have both plugins to work together by relying on a "bug" (the fact that markdown-it-toc ignores the heading token attributes): just pass the [markdown-it-toc title transform function](https://github.com/samchrisinger/markdown-it-toc/blob/c2af827db5493d4ccfdbd65153fbef4582f22772/index.js#L65-L67) to markdown-it-anchor with the `slugify` option so the `href` links to the markdown-it-toc anchors.

But I'm afraid you'll have to copy/paste this function since markdown-it-toc don't expose it, and you'll run into bugs if the plugin ever updates this function while you have the old version.

Also, if markdown-it-toc updates its renderer to consider the token attributes (fixing the "bug" you'll rely on), you'll end up with duplicate IDs, one on the heading and one on the anchor, making your HTML invalid.

---

But if we look at the problem another way, you just want to add a `#` inside the empty anchor markdown-it-toc adds to each heading, and a `href` with the ID of the same anchor.

You can achieve this by writing your own plugin:

```js
function permalink (md) {
  var originalHeadingOpen = md.renderer.rules.heading_open

  md.renderer.rules.heading_open = function (tokens, index) {
    var html = originalHeadingOpen.apply(this, arguments)

    // Transform the HTML to add a `#` inside the anchor and a `href`.

    return html
  }
}


var md = markdownIt(opts)
  .use(markdownItToc)
  .use(permalink)
```

**Comment by MoOx** [comment]
I came to the same conclusions.

But I don't like to rely on a bug, so I am working on a new plugin "markdown-it-toc-and-anchor". I will let you know when it's ready ;)

**Comment by MoOx** [comment]
https://github.com/MoOx/markdown-it-toc-and-anchor

**Comment by valeriangalliat** [comment]
Pretty nice!
