### ISSUE TITLE
How about add ES Modules support?

### ISSUE THREAD

**Issue by Jack-Kingdom** [valeriangalliat/markdown-it-anchor#46]
Build failed when integrated with React:
```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/markdown-it-anchor/index.js:1

Read more here: http://bit.ly/2tRViJ9
```

**Comment by srallen** [comment]
The issue is with the spread on this line: 
https://github.com/valeriangalliat/markdown-it-anchor/blob/1cc288c84ddac11a7047f2adb301b6958929ff19/index.js#L30

This feature is supported in Node 10, but version 10 isn't LTS yet, so I don't think it's reasonable to expect people to be upgraded yet. It's also not fully supported in IE or Edge.

To work around it, you must include this package in your babel compiling using webpack, browserify, etc.

**Comment by nagaozen** [comment]
Branch 2019-stack should fix this.
