### ISSUE TITLE
Headers with special characters between words should be converted to "-"

### ISSUE THREAD

**Issue by LeonnardoVerol** [valeriangalliat/markdown-it-anchor#67]
## Bug report

When creating headers with special characters between words, is it expected that the special character will be changed to "-"

#### Steps to reproduce

Create duplicated Headers (same name) inside a markdown file
```
# header & header
```

#### What is expected?
The anchor link for the header should be:
```
#header--header
```

#### What is actually happening?
It is generating the following anchor links:
```
#header-header
```

**Comment by nagaozen** [comment]
This library is "slugification" agnostic. _id est_ we don't decide what is the right or wrong way to make your links prettier. The default behavior is to just take the header content and `encodeURIComponent` it. That said, in the early days we leveraged the `slugify` library and it's expected output for your input is `header-and-header`, but we don't expect it as a dependency anymore.

Developers are free to decide what strategy is better for'em because they know more their application use cases than us. So, just pass a `slugify` function that tastes good for you.

Have a nice day.
