### ISSUE TITLE
Feature request: make start index configurable

### ISSUE THREAD

**Issue by adamsoffer** [valeriangalliat/markdown-it-anchor#74]
I noticed the index of anchors ids [starts at index 2](https://github.com/valeriangalliat/markdown-it-anchor/blob/master/index.js#L38). It would be great if this start index could be configurable. My use case is that I'm using[`markdown-toc`](https://github.com/jonschlinkert/markdown-toc) which uses the same naming conventions for anchors but starts at 1.

**Comment by valeriangalliat** [comment]
Hey! That a good use case, I just released 6.0.0 with a `uniqueSlugStartIndex` option to configure that.

I also made the default 1 (which is why I bumped a major) because since it seems to be the default in most other packages (and on GitHub itself) so I think it's probably a more sensible default than 2.

Cheers!

**Comment by adamsoffer** [comment]
Nice! Thanks @valeriangalliat
